dist: precise

language: php

php:
  - 7.2
  - 7.3

addons:
  mariadb: 10.4

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homas_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed --no-interaction -vvv

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/psalm --show-info=false
  - vendor/bin/php-cs-fixer fix
  - php artisan code:analyse


after_success:
    - bash <(curl -s https://codecov.io/bash)

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files
    - node_modules
    - vendor
