language: php

php:
  - 7.3

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homas_test;'
  - composer self-update
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed --no-interaction -vvv
  - php artisan config:cache
  - php artisan route:cache

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/psalm --show-info=false
  - vendor/bin/php-cs-fixer fix
  - php artisan code:analyse


after_success:
    - bash <(curl -s https://codecov.io/bash)

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files
    - node_modules
    - vendor
