commit_message: '[skip ci]'
files:
  - source: /resources/lang/en/*.php
    translation: /resources/lang/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        'en-GB' : 'en-GB'
        'pt-BR' : 'pt-BR'
        'zh-CN' : 'zh'
        'zh-TW' : 'zh-TW'
