name: Build and test

on:
  push:
    branches:
      - main
      - release
      - next
      - alpha
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

  workflow_run:
    workflows:
      - Compress images
    types: [completed]

jobs:
  #############
  # Run tests
  #############
  tests:
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.connection }} (PHP ${{ matrix.php-version }})

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: officelife
          MYSQL_DATABASE: officelife
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      pgsql:
        image: postgres:13.0
        env:
          POSTGRES_DB: officelife
          POSTGRES_USER: officelife
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php-version: [7.4, 8.0]
        connection: [sqlite, mysql, pgsql]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo, ${{ matrix.connection }}
          coverage: none
      - name: Check PHP Version
        run: php -v
      - name: Check Composer Version
        run: composer -V
      - name: Check PHP Extensions
        run: php -m

    # Composer
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer files
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-composer-${{ matrix.php-version }}

      - name: Install composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-req=php

    # Prepare
      - name: Prepare environment
        run: |
          cp tests/.env.ci-${{ matrix.connection }} .env
          touch config/version
          touch config/release
          echo '{"/js/app.js": "/js/app.js", "/css/app.css": "/css/app.css"}' > public/mix-manifest.json
          mkdir -p public/js
          echo '' > public/js/app.js
          mkdir -p public/css
          echo '' > public/css/app.css
      - name: Create SQLite database
        if: matrix.connection == 'sqlite'
        run: touch database/database.sqlite

      - name: Generate key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --no-interaction -vvv
      - name: Run seeds
        run: php artisan db:seed --no-interaction -vvv

    # Test
      - name: Run Unit test suite with coverage
        if: matrix.connection == 'mysql'
        run: phpdbg -dmemory_limit=4G -qrr vendor/bin/phpunit -c phpunit.xml --testsuite Unit --log-junit ./results/${{ matrix.connection }}/results1.xml --coverage-clover ./results/${{ matrix.connection }}/coverage.xml
        env:
          DB_CONNECTION: ${{ matrix.connection }}
      - name: Run Unit test suite
        if: matrix.connection != 'mysql'
        run: vendor/bin/phpunit -c phpunit.xml --testsuite Unit --log-junit ./results/${{ matrix.connection }}/results1.xml
        env:
          DB_CONNECTION: ${{ matrix.connection }}
      - name: Run Integration test suite
        if: matrix.connection == 'sqlite'
        run: vendor/bin/phpunit -c phpunit.xml --testsuite Integration --log-junit ./results/${{ matrix.connection }}/results2.xml
        env:
          DB_CONNECTION: ${{ matrix.connection }}

      - name: Store results
        if: matrix.php-version == '7.4'
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results

  ###########################
  # Reporting to sonarcloud
  ###########################
  reporting:
    needs: tests
    runs-on: ubuntu-latest
    name: Sonarcloud
    if: ${{ ! startsWith(github.ref, 'dependabot/') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - name: Checkout HEAD
        if: github.event_name == 'pull_request'
        run: git checkout HEAD^2

      - name: Download results
        uses: actions/download-artifact@v2
        with:
          name: results
          path: results

      - name: Fix results files
        run: sed -i -e "s%$GITHUB_WORKSPACE/%%g" results/*/*.xml

      - name: Set version parameter
        id: version
        run: |
          version=$(git tag --points-at HEAD)
          test -z "$version" && version="main"
          echo "::set-output name=value::$version"

      - name: SonarCloud Scan
        if: env.SONAR_TOKEN != ''
        uses: SonarSource/sonarcloud-github-action@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectVersion=${{ steps.version.outputs.value }}


  ####################
  # Semantic release
  ####################
  semantic-release:
    needs: tests
    runs-on: ubuntu-latest
    name: Semantic release
    if: github.event_name != 'pull_request'

    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Get all tags

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_RELEASE }}
        with:
          semantic_version: 17.3.7
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec

      - name: New release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Store changelog file
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

  package:
    needs: semantic-release
    runs-on: ubuntu-latest
    name: Package release
    if: needs.semantic-release.outputs.new_release_published == 'true'

    strategy:
      matrix:
        php-version: [7.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: v${{ needs.semantic-release.outputs.new_release_version }}
      - name: Download changelog file
        uses: actions/download-artifact@v2
        with:
          name: changelog

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo
          coverage: none

    # Composer
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer files
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-composer-${{ matrix.php-version }}

    # Yarn
      - name: Get yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn files
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Create package
        id: package
        run: scripts/package.sh 'v${{ needs.semantic-release.outputs.new_release_version }}'

      - name: Import key
        run: echo -e "$GPG_KEY" | gpg --batch --yes --import -
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      - name: Sign package
        run: |
          sha512sum '${{ steps.package.outputs.package }}' > '${{ steps.package.outputs.package }}.sha512'
          for f in '${{ steps.package.outputs.package }}'{,.sha512}; do
            echo "Signing '$f'..."
            echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode=loopback --local-user $GPG_FINGERPRINT --sign --armor --detach-sig --output "$f.asc" "$f"
            echo -e "\nSigned with key fingerprint $GPG_FINGERPRINT" >> "$f.asc"
          done
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}

      - name: Publish package
        run: |
          for f in '${{ steps.package.outputs.package }}'{,.asc,.sha512,.sha512.asc}; do
            echo "Uploading release file '$f'..."
            gh release upload 'v${{ needs.semantic-release.outputs.new_release_version }}' "$f" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store package
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ${{ steps.package.outputs.package }}
